name: bam13am
favicon: null
layout_spectrum: 0.77158
typography_spectrum: 0.84021
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1f2ed'
    - '#b28969'
    - '#222014'
    - '#bfbbb2'
    - '#7c5840'
  brandStrength: 0
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
