name: bam13am
favicon: null
layout_spectrum: 0.5076078947167844
typography_spectrum: 0.02710598846897483
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.745614695828408
  lightness: 0.27405708213336766
  saturation: 0.28789019398391247
  rhythmicContrast: 0.6883525894954801
purpose: []
